# Generated by Django 5.0.6 on 2024-06-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_customer_id',
        ),
    ]
